Importing the necessary libraries

In [286]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from math import exp
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [287]:
Crypto=pd.read_csv('/content/Crypto.csv')

Exploratory Data Analysis\
1) Checking the shape of the data


In [288]:
Crypto.shape

(17199, 19)

In [289]:
#Crypto.head()

In [290]:
#Crypto.info()

In [291]:
Crypto["CoinName"].unique()

array(['ADA', 'BTC', 'DOT', 'ETH', 'LTC', 'MATIC', 'SOL', 'TRX', 'XRP',
       'DOGE'], dtype=object)

In [292]:
Crypto = Crypto[Crypto['CoinName'] == 'DOGE']
Crypto.shape

(1906, 19)

In [293]:
Crypto.drop(['Adj Close','Date','CoinName'],axis=1,inplace=True)

<ipython-input-293-56bf2d46f121>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Crypto.drop(['Adj Close','Date','CoinName'],axis=1,inplace=True)


In [294]:
Crypto.columns=['Open', 'High', 'Low', 'Close', 'Volume',
'HighLow', 'rt_1', 'rt_2', 'rt_3', 'rt_4', 'rt_5', 'MA','lr3', 'lr5', 'lr5_lr3',
'Movement']

In [295]:
#Crypto.head()

In [296]:
Crypto.Movement.value_counts()

-1    975
 1    931
Name: Movement, dtype: int64

In [297]:
x = Crypto.drop('Movement', axis = 1)
y = Crypto['Movement']

In [298]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [299]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [300]:
cols=x.columns
x_train = pd.DataFrame(x_train, columns=cols)
x_test = pd.DataFrame(x_test, columns=cols)


In [301]:
from sklearn.linear_model import LogisticRegression
LRmodel = LogisticRegression()
LRmodel.fit(x_train, y_train)

LogisticRegression()

In [302]:
x_test_prediction = LRmodel.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)
print(classification_report(y_test,x_test_prediction))
confusion_matrix(y_test, x_test_prediction )

Accuracy score on Test Data :  0.6121593291404612
              precision    recall  f1-score   support

          -1       0.58      0.73      0.65       232
           1       0.66      0.50      0.57       245

    accuracy                           0.61       477
   macro avg       0.62      0.62      0.61       477
weighted avg       0.62      0.61      0.61       477



array([[170,  62],
       [123, 122]])

In [303]:
from sklearn.ensemble import RandomForestClassifier
rfc_100 = RandomForestClassifier(n_estimators=100, random_state=0)
rfc_100.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [304]:
y_pred_100 = rfc_100.predict(x_test)
print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))
print(classification_report(y_test,y_pred_100))
confusion_matrix(y_test, y_pred_100 )

Model accuracy score with 100 decision-trees : 0.6101
              precision    recall  f1-score   support

          -1       0.58      0.69      0.63       232
           1       0.64      0.54      0.59       245

    accuracy                           0.61       477
   macro avg       0.61      0.61      0.61       477
weighted avg       0.62      0.61      0.61       477



array([[159,  73],
       [113, 132]])

In [305]:
#clf = RandomForestClassifier(n_estimators=100, random_state=0)
#clf.fit(x_train, y_train)
#feature_scores = pd.Series(clf.feature_importances_, index= x_train.columns).sort_values(ascending=False)
#feature_scores

In [306]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [307]:
from sklearn import neighbors
from sklearn.metrics import f1_score
f1_list=[]
k_list=[]
for k in range(1,15):
  clf=neighbors.KNeighborsClassifier(n_neighbors=k,n_jobs=-1)
  clf.fit(x_train,y_train)
  pred=clf.predict(x_test)
  f=f1_score(y_test,pred,average='macro')
  f1_list.append(f)
  k_list.append(k)
best_f1_score=max(f1_list)
best_k=k_list[f1_list.index(best_f1_score)]
print("Optimum K value=",best_k)

Optimum K value= 13


In [308]:
classifier= KNeighborsClassifier(n_neighbors=11, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)
y_pred= classifier.predict(x_test)
print("Accuracy score=",classifier.score(x_test,y_test))
print(classification_report(y_test,y_pred))
confusion_matrix(y_test, y_pred)

Accuracy score= 0.49056603773584906
              precision    recall  f1-score   support

          -1       0.48      0.54      0.51       232
           1       0.50      0.44      0.47       245

    accuracy                           0.49       477
   macro avg       0.49      0.49      0.49       477
weighted avg       0.49      0.49      0.49       477



array([[126, 106],
       [137, 108]])

In [309]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [310]:
y_pred= classifier.predict(x_test)
print("Accuracy score of the model=",accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))
confusion_matrix(y_test, y_pred)

Accuracy score of the model= 0.5052410901467506
              precision    recall  f1-score   support

          -1       0.49      0.50      0.50       232
           1       0.52      0.51      0.51       245

    accuracy                           0.51       477
   macro avg       0.51      0.51      0.51       477
weighted avg       0.51      0.51      0.51       477



array([[116, 116],
       [120, 125]])

In [311]:
#Crypto.corr()

In [312]:
Crypto.drop(['High', 'Low', 'Close', 'HighLow','Open','MA','rt_4','rt_5','lr5'],axis=1, inplace=True)

In [313]:
#Crypto.corr()

In [314]:
from sklearn.datasets import make_classification
from sklearn.naive_bayes import BernoulliNB

In [315]:
X = Crypto.drop('Movement', axis = 1)
Y = Crypto['Movement']


In [316]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)
bnb = BernoulliNB(binarize=0.0)
bnb.fit(X_train, Y_train)


BernoulliNB()

In [317]:
Y_pred= bnb.predict(X_test)
print('Accuracy of the model =' ,bnb.score(X_test, Y_test))
print(classification_report(Y_test,Y_pred))
confusion_matrix(Y_test, Y_pred)

Accuracy of the model = 0.5235602094240838
              precision    recall  f1-score   support

          -1       0.52      0.54      0.53       190
           1       0.53      0.51      0.52       192

    accuracy                           0.52       382
   macro avg       0.52      0.52      0.52       382
weighted avg       0.52      0.52      0.52       382



array([[103,  87],
       [ 95,  97]])